### ISSUE TITLE
Id method in Npolar::Rack::Request fails on PUT

### ISSUE THREAD

**Issue by cnrdh** [npolar/api.npolar.no#65]
```
F, [2015-10-08T14:05:00.136845 #4415] FATAL -- : NoMethodError: undefined method `gsub' for nil:NilClass
F, [2015-10-08T14:05:00.136991 #4415] FATAL -- : Backtrace:
	/home/api/api.npolar.no/lib/npolar/rack/request.rb:109:in `id'
	/home/api/api.npolar.no/lib/npolar/rack/middleware.rb:127:in `error_hash'
	/home/api/api.npolar.no/lib/npolar/rack/middleware.rb:157:in `http_error'
	/home/api/api.npolar.no/lib/npolar/api/core.rb:120:in `handle'
	/home/api/api.npolar.no/lib/npolar/api/core.rb:39:in `call'
	/home/api/.rvm/gems/ruby-2.1.3/bundler/gems/rack-gouncer-fa1a13eacd40/lib/rack/gouncer.rb:39:in `call'
	/home/api/.rvm/gems/ruby-2.1.3/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/home/api/.rvm/gems/ruby-2.1.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/home/api/.rvm/gems/ruby-2.1.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/home/api/.rvm/gems/ruby-2.1.3/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/home/api/api.npolar.no/lib/npolar/api/json.rb:170:in `call'
	/home/api/api.npolar.no/lib/npolar/rack/edit_log.rb:28:in `handle'
	/home/api/api.npolar.no/lib/npolar/rack/middleware.rb:47:in `call'
	/home/api/.rvm/gems/ruby-2.1.3/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/home/api/.rvm/gems/ruby-2.1.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/home/api/.rvm/gems/ruby-2.1.3/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/home/api/.rvm/gems/ruby-2.1.3/bundler/gems/rack-contrib-0dc5f614be17/lib/rack/contrib/try_static.rb:33:in `call'
	/home/api/.rvm/gems/ruby-2.1.3/bundler/gems/rack-contrib-0dc5f614be17/lib/rack/contrib/jsonp.rb:39:in `call'
	/home/api/.rvm/gems/ruby-2.1.3/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
	/home/api/.rvm/gems/ruby-2.1.3/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
	/home/api/.rvm/gems/ruby-2.1.3/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
	/home/api/.rvm/gems/ruby-2.1.3/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
	/home/api/.rvm/gems/ruby-2.1.3/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
	/home/api/.rvm/gems/ruby-2.1.3/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
	/home/api/.rvm/gems/ruby-2.1.3/bin/unicorn:23:in `load'
	/home/api/.rvm/gems/ruby-2.1.3/bin/unicorn:23:in `<main>'
	/home/api/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
	/home/api/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
E, [2015-10-08T14:05:00.137226 #4415] ERROR -- : app error: undefined method `gsub' for nil:NilClass (NoMethodError)
E, [2015-10-08T14:05:00.137397 #4415] ERROR -- : /home/api/api.npolar.no/lib/npolar/rack/request.rb:109:in `id'
```

**Comment by cnrdh** [comment]
Fixed in 62b1900ef0af4f30c573a84ca00953f1c6ecf8ee
